language: php
php:
  - 7.1
  - 7.2

env:
  - ES_VERSION=6.8.5

install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &

before_script:
  - composer require elasticsearch/elasticsearch:^${ES_VERSION:0:1} --no-interaction --prefer-dist
  - sleep 10

script:
  - vendor/bin/phpunit